### ISSUE TITLE
Renamed columns are sometimes ignored.

### ISSUE THREAD

**Issue by johncarney** [ctran/annotate_models#205]
Whenever you have a migration that loads an ActiveRecord model, then a subsequent migration that renames a column on the relevant table, model annotations use the old column name.

One way to fix this would be to to invoke `reset_column_information` on models before annotating them.

**Comment by brian-vogogo** [comment]
I have some new columns getting ignored. Adding this:

`ActiveRecord::Base.descendants.each { |m| m.reset_column_information }`

to the `annotate_models` task in `annotate_models.rake` fixes the problem.

**Comment by brian-vogogo** [comment]
More info
* the models are used in a migration to modify data
* a different migration modifies the structure of the table
* we run `rake db:drop db:create db:migrate` which runs through every migration

**Comment by alexch** [comment]
On Fri, Feb 20, 2015 at 6:08 PM, Brian Low <notifications@github.com> wrote:

> the models are used in a migration to modify data


That's your problem. That's a no-no... if you need to use a model inside a
migration, make a dummy version inside the migration class itself, e.g.

```
class ChangeSomeFoos < ActiveRecord::Migration
  class Foo < ActiveRecord::Base
  end

  def change
    Foo.where(bar: true).each{|foo| foo.whatever}
  end
end
```

Otherwise your migration may break if it's run inside a later version of
the code (like one where the model is renamed, or no longer has the method
you need).

Doing `reset_column_information` is not necessarily a bad idea, but it's
cleaning up after a bad practice.
