### ISSUE TITLE
Integrate custom comments with annotation?

### ISSUE THREAD

**Issue by MatthiasWinkelmann** [ctran/annotate_models#311]
I seem to be too stupid to find a way to add any custom documentation in such a way that both the annotation and the custom content is rendered by yard. Is there a way to do this?

**Comment by jpickwell** [comment]
Model annotations support a wrapper (wrapper_open, wrapper_close, and wrapper [open and close are set to this if they are falsey]). Routes does not support the wrapper (this is a bug in my opinion). Annotate uses a simple prepend-system, instead of a more robust insert-system, so the wrapper is the only way to add custom comments, if you want the same custom comments for every model.

**Comment by ctran** [comment]
The best way to have it do what you want is to do a PR :-)

**Comment by amingilani** [comment]
@ctran I wouldn't mind lending a hand on this. What's the workaround, though? And would you entertain the possibility of adding a wrapper by default?

**Comment by amingilani** [comment]
By workaround, I mean, is there anyway I can write custom documentation for my Models without devise rewriting them? It kinda plays hell with my Yard docs.

**Comment by aaronmallen** [comment]
+1 I would also like to see custom templates & or just a yardocs parser in addition to the already existent rdocs, bare, and markdown parsers.

**Comment by amingilani** [comment]
Workaround: Enable wrappers in the initializers file, leave an empty line after the annotation, and then write your comments right about the class
