### ISSUE TITLE
add support for jsonapi `app/resources`

### ISSUE THREAD

**Issue by shadowbq** [ctran/annotate_models#350]
`app/resources`
jsonapi-resource provides a framework for developing a server that complies with the JSON API specification.

gem 'jsonapi-resources'

https://github.com/cerebris/jsonapi-resources

app/resources have to be explicitly listed so annotating the model above them would be very helpful.

**Comment by NuckChorris** [comment]
Totally agree.  Is there any reason annotate_models isn't extensible (other than manpower)?  I feel like something like this in an `.annotaterc` file could solve this issue:

```ruby
annotate 'app/resources/*_resource.rb' do |file|
  file.basename.match(/(.*)_resource.rb/)[0].classify
end
```

Where you just return a class name (or class itself) of a model based on the file you are passed.  That way if somebody uses JR instead of AMS (I certainly do), it could be annotated without modifying annotate_models

**Comment by shadowbq** [comment]
:+1:
