### ISSUE TITLE
Error when running annoate: fileless_io.rb expected to defined *Fileless_Io*, not *Fileless_IO*

### ISSUE THREAD

**Issue by stabenfeldt** [ctran/annotate_models#501]
Is this a bug in annotate or should I name my files different?
If I rename the class to **FilelessIo**, then everything works.

```
app/models/fileless_io.rb
  class FilelessIO < StringIO
```

**Comment by ragesoss** [comment]
I think this is a bug in annotate. With my similarly-named model that has an all-caps word in it, everything else in the app works fine with this naming scheme, I just have to temporarily change the file name in order to get `annotate` to run.

It it can't be easily taught to recognize class names like that, maybe an interim solution could be to just warn and skip rather than throw an error.

**Comment by sashabelozerov** [comment]
It's already working with `develop` branch.
