### ISSUE TITLE
2.7.3 Inheritance and specify table_name_prefix does not work ( Ruby on rails )

### ISSUE THREAD

**Issue by YumaInaura** [ctran/annotate_models#562]
When `super_users` table exists in sqlite

```rb
class Super < ApplicationRecord
  # does not work
  self.table_name_prefix = 'super_'

  # work
  # self.table_name = 'super_users'
end

class User < Super
  # does not work
  # self.table_name_prefix = 'super_'

  # work
  # self.table_name = 'super_users'
end

# class User < ApplicationRecord
  # work
  # self.table_name_prefix = 'super_'
# end
```

# command

```
$ bundle exec annotate app/models/user.rb
Model files unchanged.
```

# Version

- annotate (2.7.3)
- rails (5.2.0)
- ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-darwin16]

**Comment by ctran** [comment]
Could you clarify what "does not work" mean?

**Comment by abepark01** [comment]
Hello!
I ran into this issue myself using a namespaced model in a standard Ruby on Rails 5.2 application.
What the OP is saying that the `table_name` is including the `table_name_prefix` .

In the example above, the expected table_name is `super_users` but `users` is being returned instead.
If you do rails g model super/user it should output the following files...

The problem is that the method `table_name` does not include the prefix `super_`.

Again, this may be an issue stemming from https://github.com/rails/rails/issues/21476

**app/models/super.rb**
```
class Super < ApplicationRecord
  self.table_name_prefix = 'super_'
end
```

**app/models/super/user.rb**
```
module
  class User
  end
end
```

**Comment by ctran** [comment]
PR is welcome.

**Comment by lazyb0ne** [comment]
another way to fix it:
In base model: 
def self.table_name
    self.prefix_str + self.class_name.underscore.pluralize
end
and it works :)

**Comment by hut8** [comment]
With even the latest version, I'm having trouble getting `annotate` to annotate some models. It's very strange, because it annotates almost all of the models in my project fine, but it skips a few.

```
Unable to annotate app/models/metabase_dashboard.rb: Mysql2::Error: Table 'dbname.metabase_dashboards' doesn't exist
Unable to annotate app/models/metabase_dashboard.rb: no implicit conversion of nil into Array
Unable to annotate app/models/project_need.rb: Mysql2::Error: Table 'dbname.project_needs' doesn't exist
Unable to annotate app/models/project_need.rb: no implicit conversion of nil into Array
```
